[program:rexmlm-horizon]
process_name=%(program_name)s
command=php /var/www/rexmlm/REXmlm/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/rexmlm-horizon.log
stopwaitsecs=3600
